Add README for conformance report calculation
apigee/registry-experimental pull request #210
Opened 2023-07-14 22:17 UTC by shrutiparabgoogle

2023-07-14 22:25 UTC, michaelyara requested changes

2023-07-14 22:25 UTC, michaelyara commented on samples/README.md
> +- The lint result artifacts are called as conformance reports, to represent how conformant an API is wrt the
"wrt" typo

2023-07-14 22:31 UTC, shrutiparabgoogle commented on samples/README.md
> +- The lint result artifacts are called as conformance reports, to represent how conformant an API is wrt the
Done

2023-07-17 17:04 UTC, michaelyara approved these changes

2023-07-17 17:05 UTC, merged